version: '2'
servides: 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: helloroman
      POSTGRES_USER: helloroman
    ports:
      - "5432:5431"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/helloroman-edu"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links: 
      - db